---
title: "PRA2"
output: html_document
date: '2022-05-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Ejercicio 1

Descripción del dataset. ¿Por qué es importante y qué pregunta/problema pretende
responder?



## Ejercicio 2

Integración y selección de los datos de interés a analizar. Puede ser el resultado de
adicionar diferentes datasets o una subselección útil de los datos originales, en base al
objetivo que se quiera conseguir.


## Ejercicio 3

Limpieza de los datos.

### 3.1 Valores vacios

¿Los datos contienen ceros o elementos vacíos? Gestiona cada uno de estos
casos.


### 3.2 Valores extremos

Identifica y gestiona los valores extremos.


## Ejercicio 4

Análisis de los datos.


### 4.1 Elección de los datos a analizar

Selección de los grupos de datos que se quieren analizar/comparar (p. e., si se
van a comparar grupos de datos, ¿cuáles son estos grupos y qué tipo de análisis
se van a aplicar?)


### 4.2  Normalidad y Homogeneidad

Comprobación de la normalidad y homogeneidad de la varianza.


### 4.3 Análisis

Aplicación de pruebas estadísticas para comparar los grupos de datos. En función
de los datos y el objetivo del estudio, aplicar pruebas de contraste de hipótesis,
correlaciones, regresiones, etc. Aplicar al menos tres métodos de análisis
diferentes


## Ejercicio 5

Representación de los resultados a partir de tablas y gráficas. Este apartado se puede
responder a lo largo de la práctica, sin necesidad de concentrar todas las
representaciones en este punto de la práctica.



## Ejercicio 6


Resolución del problema. A partir de los resultados obtenidos, ¿cuáles son las
conclusiones? ¿Los resultados permiten responder al problema?



## Referencias